default_platform(:android)

platform :android do
  desc "Dummy lane to test fastlane setup"
  lane :hello do
    sh("echo 'Hello ...'")
  end

  desc "lane to update build number"
  lane :update_build_number do
    puts "GOOGLE_APPLICATION_CREDENTIALS"
    puts ENV['GOOGLE_APPLICATION_CREDENTIALS']
    puts "APP_ID"
    puts ENV['APP_ID']
    # get the latest release from Firebase App Distribution
    latest_release = firebase_app_distribution_get_latest_release(
    app: ENV['APP_ID'],)
    
    # if no releases found, set build_number to 1, otherwise increment the latest release version
    build_number = 1
    if(latest_release.nil?)
      puts "No releases found."
    else
      build_number =  latest_release[:buildVersion].to_i + 1
    end

    flutter_versioner(
      version_component:"version_code",
      value:"#{build_number}"
      )
  end

  lane :build_apk do
    Dir.chdir '../..' do
      sh("flutter","build","apk",)
    end
  end

  lane :distribute do
  firebase_app_distribution(
    app: ENV['APP_ID'],
    apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
    )  
  end


end #end platform :android
