name: Build and Publish
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Flutter    
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: 3.32.0
          
      - name: Install dependencies
        run: flutter pub get