name: Build and Publish #name of the workflow
on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs: # Define the jobs
  build: # Build job 
    runs-on: ubuntu-latest # The job will run on the latest Ubuntu environment
    steps:
      - name: Checkout code   # Checkout the repository code
        uses: actions/checkout@v2 
      
      - name: Setup Flutter # Setup Flutter environment
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: 3.32.0

      - name: Install dependencies # Install Flutter dependencies
        run: flutter pub get

      - name: Set up Ruby    #Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      
      - name: Create credentials file # write the json content from secrets to service-account.json
        run: echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_ENCODED }}" | base64 -d > ${{ github.workspace }}/service-account.json

      - name: Set environment variable for Google credentials #export the file path to GOOGLE_APPLICATION_CREDENTIALS
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/service-account.json" >> $GITHUB_ENV
      
      - name: Set environment variable for APP_ID #export the APP_ID
        run: echo "APP_ID=${{ secrets.APP_ID }}" >> $GITHUB_ENV
      
      - name: Install dependencies
        run: |
          cd android 
          bundle install

      - name: Update Build Number
        run: |
          cd android
          bundle exec fastlane update_build_number
      
      - name: Generate APK
        run: |
          cd android
          bundle exec fastlane build_apk

      - name: Distribute APK
        run: |
          cd android
          bundle exec fastlane distribute